/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetExcludingId model module.
 * @module model/AssetExcludingId
 * @version 3.0.1
 */
class AssetExcludingId {
    /**
     * Constructs a new <code>AssetExcludingId</code>.
     * (Schema options: { exclude: [ &#39;id&#39; ] })
     * @alias module:model/AssetExcludingId
     * @param assetGroupId {Number} ID of AssetGroup that Asset belongs to
     */
    constructor(assetGroupId) { 
        
        AssetExcludingId.initialize(this, assetGroupId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetGroupId) { 
        obj['assetGroupId'] = assetGroupId;
    }

    /**
     * Constructs a <code>AssetExcludingId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetExcludingId} obj Optional instance to populate.
     * @return {module:model/AssetExcludingId} The populated <code>AssetExcludingId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetExcludingId();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('assetGroupId')) {
                obj['assetGroupId'] = ApiClient.convertToType(data['assetGroupId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Asset name
 * @member {String} name
 */
AssetExcludingId.prototype['name'] = undefined;

/**
 * Asset description
 * @member {String} description
 */
AssetExcludingId.prototype['description'] = undefined;

/**
 * ID of AssetGroup that Asset belongs to
 * @member {Number} assetGroupId
 */
AssetExcludingId.prototype['assetGroupId'] = undefined;






export default AssetExcludingId;

