/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserWithRelations from './UserWithRelations';

/**
 * The DataLoggerWithRelations model module.
 * @module model/DataLoggerWithRelations
 * @version 3.0.1
 */
class DataLoggerWithRelations {
    /**
     * Constructs a new <code>DataLoggerWithRelations</code>.
     * (Schema options: { includeRelations: true })
     * @alias module:model/DataLoggerWithRelations
     * @param connectionType {String} Method used by DataLogger to send data to the system. At present only FTP implemented
     * @param fileFormat {String} Format of the files uploaded to the system DataLogger. At present system supports CSV and XML formats
     * @param autoInit {Boolean} Flag for selecting if DataLogger is to be initiated automatically from preexisting configuration
     * @param dataCompressed {Boolean} Flag for selecting if DataLogger sends compressed files
     * @param userId {Number} ID of User that DataLogger belongs to
     */
    constructor(connectionType, fileFormat, autoInit, dataCompressed, userId) { 
        
        DataLoggerWithRelations.initialize(this, connectionType, fileFormat, autoInit, dataCompressed, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, connectionType, fileFormat, autoInit, dataCompressed, userId) { 
        obj['connectionType'] = connectionType;
        obj['fileFormat'] = fileFormat;
        obj['autoInit'] = autoInit;
        obj['dataCompressed'] = dataCompressed;
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>DataLoggerWithRelations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataLoggerWithRelations} obj Optional instance to populate.
     * @return {module:model/DataLoggerWithRelations} The populated <code>DataLoggerWithRelations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataLoggerWithRelations();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('connectionType')) {
                obj['connectionType'] = ApiClient.convertToType(data['connectionType'], 'String');
            }
            if (data.hasOwnProperty('fileFormat')) {
                obj['fileFormat'] = ApiClient.convertToType(data['fileFormat'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('passwd')) {
                obj['passwd'] = ApiClient.convertToType(data['passwd'], 'String');
            }
            if (data.hasOwnProperty('authToken')) {
                obj['authToken'] = ApiClient.convertToType(data['authToken'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], 'String');
            }
            if (data.hasOwnProperty('autoInit')) {
                obj['autoInit'] = ApiClient.convertToType(data['autoInit'], 'Boolean');
            }
            if (data.hasOwnProperty('dataCompressed')) {
                obj['dataCompressed'] = ApiClient.convertToType(data['dataCompressed'], 'Boolean');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserWithRelations.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * Automatically generated ID
 * @member {Number} id
 */
DataLoggerWithRelations.prototype['id'] = undefined;

/**
 * Datalogger description
 * @member {String} description
 */
DataLoggerWithRelations.prototype['description'] = undefined;

/**
 * Method used by DataLogger to send data to the system. At present only FTP implemented
 * @member {String} connectionType
 */
DataLoggerWithRelations.prototype['connectionType'] = undefined;

/**
 * Format of the files uploaded to the system DataLogger. At present system supports CSV and XML formats
 * @member {String} fileFormat
 */
DataLoggerWithRelations.prototype['fileFormat'] = undefined;

/**
 * Username of system FTP account, where the DataLogger sends the data (if applicable)
 * @member {String} username
 */
DataLoggerWithRelations.prototype['username'] = undefined;

/**
 * Password of system FTP account, where the DataLogger sends the data (if applicable)
 * @member {String} passwd
 */
DataLoggerWithRelations.prototype['passwd'] = undefined;

/**
 * Authentication token of DataLogger
 * @member {String} authToken
 */
DataLoggerWithRelations.prototype['authToken'] = undefined;

/**
 * JSON configuration file for DataLogger
 * @member {String} config
 */
DataLoggerWithRelations.prototype['config'] = undefined;

/**
 * Flag for selecting if DataLogger is to be initiated automatically from preexisting configuration
 * @member {Boolean} autoInit
 */
DataLoggerWithRelations.prototype['autoInit'] = undefined;

/**
 * Flag for selecting if DataLogger sends compressed files
 * @member {Boolean} dataCompressed
 */
DataLoggerWithRelations.prototype['dataCompressed'] = undefined;

/**
 * ID of User that DataLogger belongs to
 * @member {Number} userId
 */
DataLoggerWithRelations.prototype['userId'] = undefined;

/**
 * @member {module:model/UserWithRelations} user
 */
DataLoggerWithRelations.prototype['user'] = undefined;






export default DataLoggerWithRelations;

