/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestDataLoggerSetupCsv2LocationSpec from './RequestDataLoggerSetupCsv2LocationSpec';

/**
 * The RequestDataLoggerSetupCsv2TimeData model module.
 * @module model/RequestDataLoggerSetupCsv2TimeData
 * @version 3.0.1
 */
class RequestDataLoggerSetupCsv2TimeData {
    /**
     * Constructs a new <code>RequestDataLoggerSetupCsv2TimeData</code>.
     * (Schema options: { exclude: [ &#39;fileFormat&#39; ] })
     * @alias module:model/RequestDataLoggerSetupCsv2TimeData
     * @param column {Number} Column containing time data
     * @param firstItemRow {Number} Row containing first value of time data in the CSV file
     * @param nextItemIteration {Number} Relevant row location of next item
     * @param timezone {module:model/RequestDataLoggerSetupCsv2LocationSpec} 
     * @param format {module:model/RequestDataLoggerSetupCsv2LocationSpec} 
     */
    constructor(column, firstItemRow, nextItemIteration, timezone, format) { 
        
        RequestDataLoggerSetupCsv2TimeData.initialize(this, column, firstItemRow, nextItemIteration, timezone, format);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, column, firstItemRow, nextItemIteration, timezone, format) { 
        obj['column'] = column;
        obj['firstItemRow'] = firstItemRow;
        obj['nextItemIteration'] = nextItemIteration;
        obj['timezone'] = timezone;
        obj['format'] = format;
    }

    /**
     * Constructs a <code>RequestDataLoggerSetupCsv2TimeData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestDataLoggerSetupCsv2TimeData} obj Optional instance to populate.
     * @return {module:model/RequestDataLoggerSetupCsv2TimeData} The populated <code>RequestDataLoggerSetupCsv2TimeData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestDataLoggerSetupCsv2TimeData();

            if (data.hasOwnProperty('column')) {
                obj['column'] = ApiClient.convertToType(data['column'], 'Number');
            }
            if (data.hasOwnProperty('firstItemRow')) {
                obj['firstItemRow'] = ApiClient.convertToType(data['firstItemRow'], 'Number');
            }
            if (data.hasOwnProperty('nextItemIteration')) {
                obj['nextItemIteration'] = ApiClient.convertToType(data['nextItemIteration'], 'Number');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = RequestDataLoggerSetupCsv2LocationSpec.constructFromObject(data['timezone']);
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = RequestDataLoggerSetupCsv2LocationSpec.constructFromObject(data['format']);
            }
        }
        return obj;
    }


}

/**
 * Column containing time data
 * @member {Number} column
 */
RequestDataLoggerSetupCsv2TimeData.prototype['column'] = undefined;

/**
 * Row containing first value of time data in the CSV file
 * @member {Number} firstItemRow
 */
RequestDataLoggerSetupCsv2TimeData.prototype['firstItemRow'] = undefined;

/**
 * Relevant row location of next item
 * @member {Number} nextItemIteration
 */
RequestDataLoggerSetupCsv2TimeData.prototype['nextItemIteration'] = undefined;

/**
 * @member {module:model/RequestDataLoggerSetupCsv2LocationSpec} timezone
 */
RequestDataLoggerSetupCsv2TimeData.prototype['timezone'] = undefined;

/**
 * @member {module:model/RequestDataLoggerSetupCsv2LocationSpec} format
 */
RequestDataLoggerSetupCsv2TimeData.prototype['format'] = undefined;






export default RequestDataLoggerSetupCsv2TimeData;

