/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestVirtualAccessRightExcludingAssetGroupId model module.
 * @module model/RequestVirtualAccessRightExcludingAssetGroupId
 * @version 3.0.1
 */
class RequestVirtualAccessRightExcludingAssetGroupId {
    /**
     * Constructs a new <code>RequestVirtualAccessRightExcludingAssetGroupId</code>.
     * (Schema options: { exclude: [ &#39;assetGroupId&#39; ] })
     * @alias module:model/RequestVirtualAccessRightExcludingAssetGroupId
     * @param userId {Number} Id of user to grant access to asset
     */
    constructor(userId) { 
        
        RequestVirtualAccessRightExcludingAssetGroupId.initialize(this, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId) { 
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>RequestVirtualAccessRightExcludingAssetGroupId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestVirtualAccessRightExcludingAssetGroupId} obj Optional instance to populate.
     * @return {module:model/RequestVirtualAccessRightExcludingAssetGroupId} The populated <code>RequestVirtualAccessRightExcludingAssetGroupId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestVirtualAccessRightExcludingAssetGroupId();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('assetId')) {
                obj['assetId'] = ApiClient.convertToType(data['assetId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Id of user to grant access to asset
 * @member {Number} userId
 */
RequestVirtualAccessRightExcludingAssetGroupId.prototype['userId'] = undefined;

/**
 * Id of asset
 * @member {Number} assetId
 */
RequestVirtualAccessRightExcludingAssetGroupId.prototype['assetId'] = undefined;






export default RequestVirtualAccessRightExcludingAssetGroupId;

