/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* (Schema options: { exclude: [ \'id\' ] })
*/
export class AssetExcludingId {
    /**
    * Asset name
    */
    'name'?: string;
    /**
    * Asset description
    */
    'description'?: string;
    /**
    * ID of AssetGroup that Asset belongs to
    */
    'assetGroupId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "assetGroupId",
            "baseName": "assetGroupId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AssetExcludingId.attributeTypeMap;
    }
}

