/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Channel {
    /**
    * Automatically generated ID
    */
    'id'?: number;
    /**
    * Enable channel monitoring - data recording - by setting to true
    */
    'monitor': boolean;
    /**
    * Timestamp
    */
    'lastTimestamp'?: Date;
    /**
    * Channel Status
    */
    'status'?: string;
    /**
    * ID of Device that Channel belongs to
    */
    'deviceId': number;
    /**
    * ID of ChannelType associated with Channel
    */
    'channelTypeId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "monitor",
            "baseName": "monitor",
            "type": "boolean"
        },
        {
            "name": "lastTimestamp",
            "baseName": "lastTimestamp",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "deviceId",
            "baseName": "deviceId",
            "type": "number"
        },
        {
            "name": "channelTypeId",
            "baseName": "channelTypeId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Channel.attributeTypeMap;
    }
}

