/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Device } from './device';
import { DeviceType } from './deviceType';

export class DeviceWithType {
    'deviceType': DeviceType;
    'device': Device;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deviceType",
            "baseName": "deviceType",
            "type": "DeviceType"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "Device"
        }    ];

    static getAttributeTypeMap() {
        return DeviceWithType.attributeTypeMap;
    }
}

