/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { RequestDataLoggerSetupXml2SearchStringStructureSplit } from './requestDataLoggerSetupXml2SearchStringStructureSplit';

/**
* (Schema options: { exclude: [ \'fileFormat\' ] })
*/
export class RequestDataLoggerSetupXml2SearchStringStructure {
    /**
    * XML key containing parent attribute
    */
    'key': string;
    /**
    * Flag for selecting if parent value is the entire string contained in the provided XML Key.  If set to true performSplit must be defined
    */
    'isString': boolean;
    'performSplit': Array<RequestDataLoggerSetupXml2SearchStringStructureSplit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "isString",
            "baseName": "isString",
            "type": "boolean"
        },
        {
            "name": "performSplit",
            "baseName": "performSplit",
            "type": "Array<RequestDataLoggerSetupXml2SearchStringStructureSplit>"
        }    ];

    static getAttributeTypeMap() {
        return RequestDataLoggerSetupXml2SearchStringStructure.attributeTypeMap;
    }
}

