/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { UserCredentialsWithRelations } from './userCredentialsWithRelations';

/**
* (Schema options: { includeRelations: true })
*/
export class UserWithRelations {
    /**
    * Automatically generated ID
    */
    'id'?: number;
    /**
    * Username
    */
    'username': string;
    /**
    * Password
    */
    'passwd'?: string;
    /**
    * Email
    */
    'email': string;
    'roles'?: Array<string>;
    /**
    * Automatically assigned flag to select if User is virtual or not
    */
    'isVirtual': boolean;
    'subscriptionReferenceCode'?: string;
    'userCredentials'?: UserCredentialsWithRelations;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "passwd",
            "baseName": "passwd",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>"
        },
        {
            "name": "isVirtual",
            "baseName": "isVirtual",
            "type": "boolean"
        },
        {
            "name": "subscriptionReferenceCode",
            "baseName": "subscriptionReferenceCode",
            "type": "string"
        },
        {
            "name": "userCredentials",
            "baseName": "userCredentials",
            "type": "UserCredentialsWithRelations"
        }    ];

    static getAttributeTypeMap() {
        return UserWithRelations.attributeTypeMap;
    }
}

