/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* (Schema options: { exclude: [ \'id\', \'email\', \'isVirtual\', \'roles\', \'subscriptionReferenceCode\' ] })
*/
export class UserExcludingIdEmailIsVirtualRolesSubscriptionReferenceCode {
    /**
    * Username
    */
    'username': string;
    /**
    * Password
    */
    'passwd'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "passwd",
            "baseName": "passwd",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserExcludingIdEmailIsVirtualRolesSubscriptionReferenceCode.attributeTypeMap;
    }
}

