/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AtmanIoT);
  }
}(this, function(expect, AtmanIoT) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AtmanIoT.NewDashboardElement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewDashboardElement', function() {
    it('should create an instance of NewDashboardElement', function() {
      // uncomment below and update the code to test NewDashboardElement
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be.a(AtmanIoT.NewDashboardElement);
    });

    it('should have the property assetId (base name: "assetId")', function() {
      // uncomment below and update the code to test the property assetId
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property deviceCategory (base name: "deviceCategory")', function() {
      // uncomment below and update the code to test the property deviceCategory
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property channelCategory (base name: "channelCategory")', function() {
      // uncomment below and update the code to test the property channelCategory
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property elementType (base name: "elementType")', function() {
      // uncomment below and update the code to test the property elementType
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property timeWindow (base name: "timeWindow")', function() {
      // uncomment below and update the code to test the property timeWindow
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property operation (base name: "operation")', function() {
      // uncomment below and update the code to test the property operation
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property groupBy (base name: "groupBy")', function() {
      // uncomment below and update the code to test the property groupBy
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property xLabel (base name: "xLabel")', function() {
      // uncomment below and update the code to test the property xLabel
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

    it('should have the property yLabel (base name: "yLabel")', function() {
      // uncomment below and update the code to test the property yLabel
      //var instane = new AtmanIoT.NewDashboardElement();
      //expect(instance).to.be();
    });

  });

}));
