// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AssetGroup
 */
export interface AssetGroup {
    /**
     * Automatically generated ID
     * @type {number}
     * @memberof AssetGroup
     */
    id?: number;
    /**
     * AssetGroup name
     * @type {string}
     * @memberof AssetGroup
     */
    name?: string;
    /**
     * AssetGroup description
     * @type {string}
     * @memberof AssetGroup
     */
    description?: string;
    /**
     * ID of User that AssetGroup belongs to
     * @type {number}
     * @memberof AssetGroup
     */
    userId: number;
}
