// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * Automatically generated ID
     * @type {number}
     * @memberof Channel
     */
    id?: number;
    /**
     * Enable channel monitoring - data recording - by setting to true
     * @type {boolean}
     * @memberof Channel
     */
    monitor: boolean;
    /**
     * Timestamp
     * @type {string}
     * @memberof Channel
     */
    lastTimestamp?: string;
    /**
     * Channel Status
     * @type {string}
     * @memberof Channel
     */
    status?: string;
    /**
     * ID of Device that Channel belongs to
     * @type {number}
     * @memberof Channel
     */
    deviceId: number;
    /**
     * ID of ChannelType associated with Channel
     * @type {number}
     * @memberof Channel
     */
    channelTypeId: number;
}
