// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * (Schema options: { exclude: [ \'id\', \'serialNo\', \'dataLoggerId\', \'deviceTypeId\' ] })
 * @export
 * @interface DeviceExcludingIdSerialNoDataLoggerIdDeviceTypeId
 */
export interface DeviceExcludingIdSerialNoDataLoggerIdDeviceTypeId {
    /**
     * Device description
     * @type {string}
     * @memberof DeviceExcludingIdSerialNoDataLoggerIdDeviceTypeId
     */
    description?: string;
}
