// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    greeting?: string;
    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    date?: string;
    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    url?: string;
    /**
     * @type {{ [key: string]: object; }}
     * @memberof InlineResponse200
     */
    headers?: { [key: string]: object; };
}
