// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SubscriptionWithRelations,
} from './';

/**
 * (tsType: UserSubscriptionWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface UserSubscriptionWithRelations
 */
export interface UserSubscriptionWithRelations {
    /**
     * @type {number}
     * @memberof UserSubscriptionWithRelations
     */
    id?: number;
    /**
     * @type {string}
     * @memberof UserSubscriptionWithRelations
     */
    referenceCode: string;
    /**
     * @type {string}
     * @memberof UserSubscriptionWithRelations
     */
    email?: string;
    /**
     * @type {number}
     * @memberof UserSubscriptionWithRelations
     */
    discount: number;
    /**
     * Timestamp
     * @type {string}
     * @memberof UserSubscriptionWithRelations
     */
    creationTimestamp: string;
    /**
     * Timestamp
     * @type {string}
     * @memberof UserSubscriptionWithRelations
     */
    activationTimestamp?: string;
    /**
     * Timestamp
     * @type {string}
     * @memberof UserSubscriptionWithRelations
     */
    endTimestamp?: string;
    /**
     * @type {boolean}
     * @memberof UserSubscriptionWithRelations
     */
    hasRegistered: boolean;
    /**
     * ID of Subscription
     * @type {number}
     * @memberof UserSubscriptionWithRelations
     */
    subscriptionId: number;
    /**
     * @type {SubscriptionWithRelations}
     * @memberof UserSubscriptionWithRelations
     */
    subscription?: SubscriptionWithRelations;
}
