# coding: utf-8

"""
    Atman IoT

    Atman IoT Server  # noqa: E501

    The version of the OpenAPI document: 3.0.1
    Contact: k.khoury@k-ren.gr
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.request_event_create_rule import RequestEventCreateRule  # noqa: E501
from openapi_client.rest import ApiException

class TestRequestEventCreateRule(unittest.TestCase):
    """RequestEventCreateRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RequestEventCreateRule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.request_event_create_rule.RequestEventCreateRule()  # noqa: E501
        if include_optional :
            return RequestEventCreateRule(
                description = '0', 
                scope = [
                    openapi_client.models.request_event_rule_scope.RequestEventRuleScope(
                        device_type_category = '0', 
                        channel_type_category = '0', )
                    ], 
                action = '0', 
                action_parameters = None
            )
        else :
            return RequestEventCreateRule(
                description = '0',
                scope = [
                    openapi_client.models.request_event_rule_scope.RequestEventRuleScope(
                        device_type_category = '0', 
                        channel_type_category = '0', )
                    ],
                action = '0',
                action_parameters = None,
        )

    def testRequestEventCreateRule(self):
        """Test RequestEventCreateRule"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
