<?php
/**
 * EventRelatedDeviceExcludingId
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Atman IoT
 *
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the EventRelatedDeviceExcludingId model.
 *
 * (Schema options: { exclude: [ &#39;id&#39; ] })
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class EventRelatedDeviceExcludingId 
{
        /**
     * ID of Device associated with Event
     *
     * @var float
     * @SerializedName("deviceId")
     * @Assert\NotNull()
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $deviceId;

    /**
     * ID of Event
     *
     * @var float
     * @SerializedName("eventId")
     * @Assert\NotNull()
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $eventId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->deviceId = isset($data['deviceId']) ? $data['deviceId'] : null;
        $this->eventId = isset($data['eventId']) ? $data['eventId'] : null;
    }

    /**
     * Gets deviceId.
     *
     * @return float
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     * Sets deviceId.
     *
     * @param float $deviceId  ID of Device associated with Event
     *
     * @return $this
     */
    public function setDeviceId($deviceId)
    {
        $this->deviceId = $deviceId;

        return $this;
    }

    /**
     * Gets eventId.
     *
     * @return float
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Sets eventId.
     *
     * @param float $eventId  ID of Event
     *
     * @return $this
     */
    public function setEventId($eventId)
    {
        $this->eventId = $eventId;

        return $this;
    }
}


