<?php
/**
 * RequestDataLoggerSetupCsv2DataHeaderLocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Atman IoT
 *
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * RequestDataLoggerSetupCsv2DataHeaderLocationTest Class Doc Comment
 *
 * @category    Class
 * @description (Schema options: { exclude: [ &#39;fileFormat&#39; ] })
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RequestDataLoggerSetupCsv2DataHeaderLocationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestDataLoggerSetupCsv2DataHeaderLocation"
     */
    public function testRequestDataLoggerSetupCsv2DataHeaderLocation()
    {
    }

    /**
     * Test attribute "first_item_col"
     */
    public function testPropertyFirstItemCol()
    {
    }

    /**
     * Test attribute "next_item_iteration"
     */
    public function testPropertyNextItemIteration()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "serial_no"
     */
    public function testPropertySerialNo()
    {
    }

    /**
     * Test attribute "channel_name"
     */
    public function testPropertyChannelName()
    {
    }

    /**
     * Test attribute "channel_unit"
     */
    public function testPropertyChannelUnit()
    {
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
    }
}
