// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Schema options: { exclude: [ \'id\', \'userId\' ] })
 * @export
 * @interface AssetGroupExcludingIdUserId
 */
export interface AssetGroupExcludingIdUserId  {
    /**
     * AssetGroup name
     * @type {string}
     * @memberof AssetGroupExcludingIdUserId
     */
    name?: string;
    /**
     * AssetGroup description
     * @type {string}
     * @memberof AssetGroupExcludingIdUserId
     */
    description?: string;
}

export function AssetGroupExcludingIdUserIdFromJSON(json: any): AssetGroupExcludingIdUserId {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AssetGroupExcludingIdUserIdToJSON(value?: AssetGroupExcludingIdUserId): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'description': value.description,
    };
}


