// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelType
 */
export interface ChannelType  {
    /**
     * Automatically generated ID
     * @type {number}
     * @memberof ChannelType
     */
    id?: number;
    /**
     * ChannelType name
     * @type {string}
     * @memberof ChannelType
     */
    name: string;
    /**
     * ChannelType category
     * @type {string}
     * @memberof ChannelType
     */
    category?: string;
    /**
     * ChannelType description
     * @type {string}
     * @memberof ChannelType
     */
    description?: string;
    /**
     * Unit of measurement
     * @type {string}
     * @memberof ChannelType
     */
    unit?: string;
    /**
     * Type of data: UNDEFINED / SPOT_VALUE / COUNTER / TEXT
     * @type {string}
     * @memberof ChannelType
     */
    channelType: string;
    /**
     * ID of DeviceType that ChannelType belongs to
     * @type {number}
     * @memberof ChannelType
     */
    deviceTypeId: number;
}

export function ChannelTypeFromJSON(json: any): ChannelType {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'channelType': json['channelType'],
        'deviceTypeId': json['deviceTypeId'],
    };
}

export function ChannelTypeToJSON(value?: ChannelType): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'category': value.category,
        'description': value.description,
        'unit': value.unit,
        'channelType': value.channelType,
        'deviceTypeId': value.deviceTypeId,
    };
}


