// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Schema options: { exclude: [ \'id\', \'authToken\', \'config\', \'userId\' ] })
 * @export
 * @interface DataLoggerExcludingIdAuthTokenConfigUserId
 */
export interface DataLoggerExcludingIdAuthTokenConfigUserId  {
    /**
     * Datalogger description
     * @type {string}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    description?: string;
    /**
     * Method used by DataLogger to send data to the system. At present only FTP implemented
     * @type {string}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    connectionType: string;
    /**
     * Format of the files uploaded to the system DataLogger. At present system supports CSV and XML formats
     * @type {string}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    fileFormat: string;
    /**
     * Username of system FTP account, where the DataLogger sends the data (if applicable)
     * @type {string}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    username?: string;
    /**
     * Password of system FTP account, where the DataLogger sends the data (if applicable)
     * @type {string}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    passwd?: string;
    /**
     * Flag for selecting if DataLogger is to be initiated automatically from preexisting configuration
     * @type {boolean}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    autoInit: boolean;
    /**
     * Flag for selecting if DataLogger sends compressed files
     * @type {boolean}
     * @memberof DataLoggerExcludingIdAuthTokenConfigUserId
     */
    dataCompressed: boolean;
}

export function DataLoggerExcludingIdAuthTokenConfigUserIdFromJSON(json: any): DataLoggerExcludingIdAuthTokenConfigUserId {
    return {
        'description': !exists(json, 'description') ? undefined : json['description'],
        'connectionType': json['connectionType'],
        'fileFormat': json['fileFormat'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'passwd': !exists(json, 'passwd') ? undefined : json['passwd'],
        'autoInit': json['autoInit'],
        'dataCompressed': json['dataCompressed'],
    };
}

export function DataLoggerExcludingIdAuthTokenConfigUserIdToJSON(value?: DataLoggerExcludingIdAuthTokenConfigUserId): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'description': value.description,
        'connectionType': value.connectionType,
        'fileFormat': value.fileFormat,
        'username': value.username,
        'passwd': value.passwd,
        'autoInit': value.autoInit,
        'dataCompressed': value.dataCompressed,
    };
}


