// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200  {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    greeting?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    url?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof InlineResponse200
     */
    headers?: { [key: string]: object; };
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return {
        'greeting': !exists(json, 'greeting') ? undefined : json['greeting'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'greeting': value.greeting,
        'date': value.date,
        'url': value.url,
        'headers': value.headers,
    };
}


