// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001LastMeasurementDCVoltage
 */
export interface InlineResponse2001LastMeasurementDCVoltage  {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    channelId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    measurement?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    unit?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    timestamp?: string;
}

export function InlineResponse2001LastMeasurementDCVoltageFromJSON(json: any): InlineResponse2001LastMeasurementDCVoltage {
    return {
        'channelId': !exists(json, 'channelId') ? undefined : json['channelId'],
        'measurement': !exists(json, 'measurement') ? undefined : json['measurement'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function InlineResponse2001LastMeasurementDCVoltageToJSON(value?: InlineResponse2001LastMeasurementDCVoltage): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'channelId': value.channelId,
        'measurement': value.measurement,
        'unit': value.unit,
        'timestamp': value.timestamp,
    };
}


