// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Schema options: { exclude: [ \'fileFormat\' ] })
 * @export
 * @interface RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray
 */
export interface RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray  {
    /**
     * First row containing parent
     * @type {number}
     * @memberof RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray
     */
    firstItemRow: number;
    /**
     * Flag to enable setting parent manually
     * @type {boolean}
     * @memberof RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray
     */
    setManually?: boolean;
    /**
     * Manual value for parent (string)
     * @type {string}
     * @memberof RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray
     */
    manualValue?: string;
}

export function RequestDataLoggerSetupCsv2DataHeaderLocationKeysArrayFromJSON(json: any): RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray {
    return {
        'firstItemRow': json['firstItemRow'],
        'setManually': !exists(json, 'setManually') ? undefined : json['setManually'],
        'manualValue': !exists(json, 'manualValue') ? undefined : json['manualValue'],
    };
}

export function RequestDataLoggerSetupCsv2DataHeaderLocationKeysArrayToJSON(value?: RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'firstItemRow': value.firstItemRow,
        'setManually': value.setManually,
        'manualValue': value.manualValue,
    };
}


