export * from './AssetControllerApi';
import { AssetControllerApi } from './AssetControllerApi';
export * from './AssetGroupControllerApi';
import { AssetGroupControllerApi } from './AssetGroupControllerApi';
export * from './DataLoggerControllerApi';
import { DataLoggerControllerApi } from './DataLoggerControllerApi';
export * from './DeviceChannelControllerApi';
import { DeviceChannelControllerApi } from './DeviceChannelControllerApi';
export * from './DeviceControllerApi';
import { DeviceControllerApi } from './DeviceControllerApi';
export * from './DeviceGroupMembershipControllerApi';
import { DeviceGroupMembershipControllerApi } from './DeviceGroupMembershipControllerApi';
export * from './DeviceTypeChannelTypeControllerApi';
import { DeviceTypeChannelTypeControllerApi } from './DeviceTypeChannelTypeControllerApi';
export * from './DeviceTypeControllerApi';
import { DeviceTypeControllerApi } from './DeviceTypeControllerApi';
export * from './EventControllerApi';
import { EventControllerApi } from './EventControllerApi';
export * from './PingControllerApi';
import { PingControllerApi } from './PingControllerApi';
export * from './SchedulerControllerApi';
import { SchedulerControllerApi } from './SchedulerControllerApi';
export * from './SolarMonitorControllerApi';
import { SolarMonitorControllerApi } from './SolarMonitorControllerApi';
export * from './UserControllerApi';
import { UserControllerApi } from './UserControllerApi';
export * from './VirtualAccessControllerApi';
import { VirtualAccessControllerApi } from './VirtualAccessControllerApi';
export const APIS = [AssetControllerApi, AssetGroupControllerApi, DataLoggerControllerApi, DeviceChannelControllerApi, DeviceControllerApi, DeviceGroupMembershipControllerApi, DeviceTypeChannelTypeControllerApi, DeviceTypeControllerApi, EventControllerApi, PingControllerApi, SchedulerControllerApi, SolarMonitorControllerApi, UserControllerApi, VirtualAccessControllerApi];
