// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';

import {
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineResponse2001,
    InlineResponse2001FromJSON,
    InlineResponse2001ToJSON,
    InlineResponse2002,
    InlineResponse2002FromJSON,
    InlineResponse2002ToJSON,
} from '../models';

export interface SolarMonitorControllerFindLastTsInvRequest {
    inlineObject?: InlineObject;
}


/**
 */
function solarMonitorControllerFindLastTsRaw<T>( requestConfig: runtime.TypedQueryConfig<T, InlineResponse2002> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `/solar-monitor/weather`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(InlineResponse2002FromJSON(body), text);
    }

    return config;
}

/**
*/
export function solarMonitorControllerFindLastTs<T>( requestConfig?: runtime.TypedQueryConfig<T, InlineResponse2002>): QueryConfig<T> {
    return solarMonitorControllerFindLastTsRaw( requestConfig);
}

/**
 */
function solarMonitorControllerFindLastTsInvRaw<T>(requestParameters: SolarMonitorControllerFindLastTsInvRequest, requestConfig: runtime.TypedQueryConfig<T, InlineResponse2001> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `/solar-monitor/inverters`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || InlineObjectToJSON(requestParameters.inlineObject),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(InlineResponse2001FromJSON(body), text);
    }

    return config;
}

/**
*/
export function solarMonitorControllerFindLastTsInv<T>(requestParameters: SolarMonitorControllerFindLastTsInvRequest, requestConfig?: runtime.TypedQueryConfig<T, InlineResponse2001>): QueryConfig<T> {
    return solarMonitorControllerFindLastTsInvRaw(requestParameters, requestConfig);
}

