/*
 * Atman IoT
 *
 * Atman IoT Server
 *
 * API version: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// DataLoggerControllerApiService is a service that implents the logic for the DataLoggerControllerApiServicer
// This service should implement the business logic for every endpoint for the DataLoggerControllerApi API. 
// Include any external packages or services that will be required by this service.
type DataLoggerControllerApiService struct {
}

// NewDataLoggerControllerApiService creates a default api service
func NewDataLoggerControllerApiService() DataLoggerControllerApiServicer {
	return &DataLoggerControllerApiService{}
}

// DataLoggerControllerCreate - 
func (s *DataLoggerControllerApiService) DataLoggerControllerCreate(dataLoggerExcludingIdAuthTokenConfigUserId DataLoggerExcludingIdAuthTokenConfigUserId) (interface{}, error) {
	// TODO - update DataLoggerControllerCreate with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerCreate' not implemented")
}

// DataLoggerControllerDeleteById - 
func (s *DataLoggerControllerApiService) DataLoggerControllerDeleteById(id float32) (interface{}, error) {
	// TODO - update DataLoggerControllerDeleteById with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerDeleteById' not implemented")
}

// DataLoggerControllerFind - 
func (s *DataLoggerControllerApiService) DataLoggerControllerFind() (interface{}, error) {
	// TODO - update DataLoggerControllerFind with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerFind' not implemented")
}

// DataLoggerControllerSetupFromFtp1 - 
func (s *DataLoggerControllerApiService) DataLoggerControllerSetupFromFtp1(id float32, dataLoggerToken string) (interface{}, error) {
	// TODO - update DataLoggerControllerSetupFromFtp1 with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerSetupFromFtp1' not implemented")
}

// DataLoggerControllerSetupFromFtp3 - 
func (s *DataLoggerControllerApiService) DataLoggerControllerSetupFromFtp3(id float32, responseDataLoggerSetupStep2 ResponseDataLoggerSetupStep2) (interface{}, error) {
	// TODO - update DataLoggerControllerSetupFromFtp3 with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerSetupFromFtp3' not implemented")
}

// DataLoggerControllerSetupFromFtpCsv2 - 
func (s *DataLoggerControllerApiService) DataLoggerControllerSetupFromFtpCsv2(id float32, requestDataLoggerSetupCsv2ExcludingFileFormat RequestDataLoggerSetupCsv2ExcludingFileFormat) (interface{}, error) {
	// TODO - update DataLoggerControllerSetupFromFtpCsv2 with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerSetupFromFtpCsv2' not implemented")
}

// DataLoggerControllerSetupFromFtpXml2 - 
func (s *DataLoggerControllerApiService) DataLoggerControllerSetupFromFtpXml2(id float32, requestDataLoggerSetupXml2ExcludingFileFormat RequestDataLoggerSetupXml2ExcludingFileFormat) (interface{}, error) {
	// TODO - update DataLoggerControllerSetupFromFtpXml2 with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerSetupFromFtpXml2' not implemented")
}

// DataLoggerControllerUploadDataFromCsv - 
func (s *DataLoggerControllerApiService) DataLoggerControllerUploadDataFromCsv(id float32, dataLoggerToken string) (interface{}, error) {
	// TODO - update DataLoggerControllerUploadDataFromCsv with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerUploadDataFromCsv' not implemented")
}

// DataLoggerControllerUploadDataFromXml - 
func (s *DataLoggerControllerApiService) DataLoggerControllerUploadDataFromXml(id float32, dataLoggerToken string) (interface{}, error) {
	// TODO - update DataLoggerControllerUploadDataFromXml with the required logic for this service method.
	// Add api_data_logger_controller_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DataLoggerControllerUploadDataFromXml' not implemented")
}
