/*
 * Atman IoT
 *
 * Atman IoT Server
 *
 * API version: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChannelType struct {

	// Automatically generated ID
	Id float32 `json:"id,omitempty"`

	// ChannelType name
	Name string `json:"name"`

	// ChannelType category
	Category string `json:"category,omitempty"`

	// ChannelType description
	Description string `json:"description,omitempty"`

	// Unit of measurement
	Unit string `json:"unit,omitempty"`

	// Type of data: UNDEFINED / SPOT_VALUE / COUNTER / TEXT
	ChannelType string `json:"channelType"`

	// ID of DeviceType that ChannelType belongs to
	DeviceTypeId float32 `json:"deviceTypeId"`
}
