# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DeviceTypeExcludingIdModelManufacturer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description=None, category=None):  # noqa: E501
        """DeviceTypeExcludingIdModelManufacturer - a model defined in OpenAPI

        :param description: The description of this DeviceTypeExcludingIdModelManufacturer.  # noqa: E501
        :type description: str
        :param category: The category of this DeviceTypeExcludingIdModelManufacturer.  # noqa: E501
        :type category: str
        """
        self.openapi_types = {
            'description': str,
            'category': str
        }

        self.attribute_map = {
            'description': 'description',
            'category': 'category'
        }

        self._description = description
        self._category = category

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceTypeExcludingIdModelManufacturer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceTypeExcluding_id-model-manufacturer_ of this DeviceTypeExcludingIdModelManufacturer.  # noqa: E501
        :rtype: DeviceTypeExcludingIdModelManufacturer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this DeviceTypeExcludingIdModelManufacturer.

        DeviceType description  # noqa: E501

        :return: The description of this DeviceTypeExcludingIdModelManufacturer.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DeviceTypeExcludingIdModelManufacturer.

        DeviceType description  # noqa: E501

        :param description: The description of this DeviceTypeExcludingIdModelManufacturer.
        :type description: str
        """

        self._description = description

    @property
    def category(self):
        """Gets the category of this DeviceTypeExcludingIdModelManufacturer.

        DeviceType category  # noqa: E501

        :return: The category of this DeviceTypeExcludingIdModelManufacturer.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this DeviceTypeExcludingIdModelManufacturer.

        DeviceType category  # noqa: E501

        :param category: The category of this DeviceTypeExcludingIdModelManufacturer.
        :type category: str
        """

        self._category = category
