/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { exclude: [ \'id\', \'assetGroupId\' ] })
 */
export interface AssetExcludingIdAssetGroupId { 
    /**
     * Asset name
     */
    name?: string;
    /**
     * Asset description
     */
    description?: string;
}

