/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventRule { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Rule description
     */
    description?: string;
    /**
     * Rule scope
     */
    scope: string;
    /**
     * Event Detection Algorithm
     */
    algorithm?: string;
    /**
     * Rule action
     */
    action: string;
    /**
     * Rule action parameters
     */
    actionParameters?: string;
    /**
     * JSON Rule
     */
    rule?: string;
    /**
     * EventRule execution period - seconds
     */
    executionPeriod?: number;
    /**
     * Last execution timestamp
     */
    lastExecTimestamp?: string;
    /**
     * Is set to true when EventRule has been activated
     */
    activated?: boolean;
    /**
     * Is automaticaly set to true when EventRule is being processed
     */
    inProgress?: boolean;
}

