// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * (Schema options: { exclude: [ \'id\', \'userId\' ] })
 * @export
 * @interface AssetGroupExcludingIdUserId
 */
export interface AssetGroupExcludingIdUserId {
    /**
     * AssetGroup name
     * @type {string}
     * @memberof AssetGroupExcludingIdUserId
     */
    name?: string;
    /**
     * AssetGroup description
     * @type {string}
     * @memberof AssetGroupExcludingIdUserId
     */
    description?: string;
}
