// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * Automatically generated ID
     * @type {number}
     * @memberof Device
     */
    id?: number;
    /**
     * Device description
     * @type {string}
     * @memberof Device
     */
    description?: string;
    /**
     * Device serial number
     * @type {string}
     * @memberof Device
     */
    serialNo: string;
    /**
     * ID of DataLogger that Device belongs to
     * @type {number}
     * @memberof Device
     */
    dataLoggerId: number;
    /**
     * ID of DeviceType associated with Device
     * @type {number}
     * @memberof Device
     */
    deviceTypeId: number;
}
