// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * Automatically generated ID
     * @type {number}
     * @memberof Event
     */
    id?: number;
    /**
     * ID of Asset associated with Event
     * @type {number}
     * @memberof Event
     */
    assetId: number;
    /**
     * ID of EventRule triggered
     * @type {number}
     * @memberof Event
     */
    eventRuleId: number;
    /**
     * Event severity - Can be  LOW / MEDIUM / HIGH
     * @type {string}
     * @memberof Event
     */
    severity: string;
    /**
     * Event description
     * @type {string}
     * @memberof Event
     */
    description?: string;
    /**
     * Set to true if Event has been resolved
     * @type {boolean}
     * @memberof Event
     */
    resolved: boolean;
    /**
     * Event creation timestamp
     * @type {string}
     * @memberof Event
     */
    timestamp: string;
    /**
     * Event resolution timestamp
     * @type {string}
     * @memberof Event
     */
    resolutionTimestamp?: string;
}
