// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InlineResponse2002Basic,
    InlineResponse2002BasicTemperature,
    InlineResponse2002Wind,
} from './';

/**
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * @type {InlineResponse2002Basic}
     * @memberof InlineResponse2002
     */
    Basic?: InlineResponse2002Basic;
    /**
     * @type {InlineResponse2002Wind}
     * @memberof InlineResponse2002
     */
    Wind?: InlineResponse2002Wind;
    /**
     * @type {InlineResponse2002BasicTemperature}
     * @memberof InlineResponse2002
     */
    SolarRadiation?: InlineResponse2002BasicTemperature;
}
