// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InlineResponse2001LastMeasurementDCVoltage
 */
export interface InlineResponse2001LastMeasurementDCVoltage {
    /**
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    channelId?: number;
    /**
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    measurement?: number;
    /**
     * @type {number}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    unit?: number;
    /**
     * @type {string}
     * @memberof InlineResponse2001LastMeasurementDCVoltage
     */
    timestamp?: string;
}
