// tslint:disable
/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders } from '../runtime';
import {
    InlineObject,
    InlineResponse2001,
    InlineResponse2002,
} from '../models';

export interface SolarMonitorControllerFindLastTsInvRequest {
    inlineObject?: InlineObject;
}

/**
 * no description
 */
export class SolarMonitorControllerApi extends BaseAPI {

    /**
     */
    solarMonitorControllerFindLastTs = (): Observable<InlineResponse2002> => {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<InlineResponse2002>({
            path: '/solar-monitor/weather',
            method: 'GET',
            headers,
        });
    };

    /**
     */
    solarMonitorControllerFindLastTsInv = ({ inlineObject }: SolarMonitorControllerFindLastTsInvRequest): Observable<InlineResponse2001> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<InlineResponse2001>({
            path: '/solar-monitor/inverters',
            method: 'POST',
            headers,
            body: inlineObject,
        });
    };

}
