/*
 * Atman IoT
 *
 * Atman IoT Server
 *
 * API version: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LoopbackCount struct for LoopbackCount
type LoopbackCount struct {
	Count float32 `json:"count,omitempty"`
}
