<?php
/**
 * DashboardElementControllerApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Atman IoT
 *
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\DashboardElement;
use OpenAPI\Server\Model\DashboardElementWithScope;
use OpenAPI\Server\Model\NewDashboardElement;

/**
 * DashboardElementControllerApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface DashboardElementControllerApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth($value);

    /**
     * Operation dashboardElementControllerCreate
     *
     * @param  OpenAPI\Server\Model\NewDashboardElement $newDashboardElement   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\DashboardElement
     *
     */
    public function dashboardElementControllerCreate(NewDashboardElement $newDashboardElement = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation dashboardElementControllerDeleteById
     *
     * @param  float $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function dashboardElementControllerDeleteById($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation dashboardElementControllerFindByUserIdAssetIdLocation
     *
     * @param  float $assetId   (required)
     * @param  float $userId   (required)
     * @param  string $location   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\DashboardElementWithScope[]
     *
     */
    public function dashboardElementControllerFindByUserIdAssetIdLocation($assetId, $userId, $location, &$responseCode, array &$responseHeaders);

    /**
     * Operation dashboardElementControllerMoveElementDown
     *
     * @param  float $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function dashboardElementControllerMoveElementDown($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation dashboardElementControllerMoveElementUp
     *
     * @param  float $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function dashboardElementControllerMoveElementUp($id, &$responseCode, array &$responseHeaders);
}
