<?php
/**
 * UserSubscriptionControllerApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Atman IoT
 *
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: k.khoury@k-ren.gr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\CodeVerificationRequest;
use OpenAPI\Server\Model\Subscription;
use OpenAPI\Server\Model\UserSubscription;
use OpenAPI\Server\Model\UserSubscriptionWithRelations;

/**
 * UserSubscriptionControllerApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface UserSubscriptionControllerApiInterface
{

    /**
     * Operation userSubscriptionControllerCreate
     *
     * @param  array $body   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function userSubscriptionControllerCreate(array $body = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation userSubscriptionControllerCreateUserSubscriptionBySubId
     *
     * @param  float $subscriptionId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\UserSubscription
     *
     */
    public function userSubscriptionControllerCreateUserSubscriptionBySubId($subscriptionId, &$responseCode, array &$responseHeaders);

    /**
     * Operation userSubscriptionControllerFindSubscriptionsByCategory
     *
     * @param  string $product   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Subscription[]
     *
     */
    public function userSubscriptionControllerFindSubscriptionsByCategory($product, &$responseCode, array &$responseHeaders);

    /**
     * Operation userSubscriptionControllerGetByRefferenceCode
     *
     * @param  string $referenceCode   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\UserSubscriptionWithRelations
     *
     */
    public function userSubscriptionControllerGetByRefferenceCode($referenceCode, &$responseCode, array &$responseHeaders);

    /**
     * Operation userSubscriptionControllerVerifyCode
     *
     * @param  OpenAPI\Server\Model\CodeVerificationRequest $codeVerificationRequest   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\UserSubscription
     *
     */
    public function userSubscriptionControllerVerifyCode(CodeVerificationRequest $codeVerificationRequest = null, &$responseCode, array &$responseHeaders);
}
